name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Verify source layout
        run: |
          ls -1
          test -d cmd/server || (echo "ERROR: cmd/server directory missing in repo" && exit 1)
          grep -R "package main" -n cmd/server || true
      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
          mkdir -p dist
          echo "Building ${{ matrix.goos }}-${{ matrix.goarch }}"
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -ldflags "-s -w -X main.commit=${{ github.sha }} -X main.buildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)" -o dist/heheswitch-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/server
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: heheswitch-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/heheswitch-${{ matrix.goos }}-${{ matrix.goarch }}
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Gather binaries
        run: |
          ls -R dist
          chmod +x dist/**/heheswitch-*
          mkdir uploads
          find dist -type f -name 'heheswitch-*' -exec mv {} uploads/ \;
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          files: uploads/heheswitch-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
